CREATE TABLE IF NOT EXISTS card (
                      card_id    BIGINT       GENERATED BY DEFAULT AS IDENTITY,
                      card_name  VARCHAR(255) NOT NULL,
                      set_name   VARCHAR(255) NOT NULL,
                      language   VARCHAR(255) NOT NULL,
                      rarity     VARCHAR(255) NOT NULL,
                      image_url  VARCHAR(255) NOT NULL,
                      PRIMARY KEY (card_id)
);

CREATE INDEX IF NOT EXISTS idx_card_card_name ON card (card_name);