apiVersion: v1
kind: ServiceAccount
metadata:
  name: datadog-agent
  namespace: datadog
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: datadog-agent
rules:
- apiGroups:
  - ""
  resources:
  - services
  - events
  - endpoints
  - pods
  - nodes
  - nodes/proxy
  - nodes/metrics
  - nodes/spec
  - nodes/stats
  - componentstatuses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - update
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- nonResourceURLs:
  - /version
  - /healthz
  - /metrics
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: datadog-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: datadog-agent
subjects:
- kind: ServiceAccount
  name: datadog-agent
  namespace: datadog
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: datadog-agent
  namespace: datadog
  labels:
    app: datadog-agent
spec:
  selector:
    matchLabels:
      app: datadog-agent
  template:
    metadata:
      labels:
        app: datadog-agent
    spec:
      serviceAccountName: datadog-agent
      tolerations:
      - operator: Exists
      containers:
      - image: gcr.io/datadoghq/agent:7
        name: datadog-agent
        env:
        - name: DD_API_KEY
          valueFrom:
            secretKeyRef:
              name: datadog-secret
              key: api-key
        - name: DD_ENV
          value: "development"
        - name: DD_SITE
          valueFrom:
            secretKeyRef:
              name: datadog-secret
              key: site
        - name: DD_HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: DD_KUBERNETES_KUBELET_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: DD_DOGSTATSD_NON_LOCAL_TRAFFIC
          value: "true"
        - name: DD_APM_NON_LOCAL_TRAFFIC
          value: "true"
        - name: DD_APM_ENABLED
          value: "true"
        - name: DD_LOGS_ENABLED
          value: "true"
        - name: DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL
          value: "true"
        - name: DD_KUBELET_TLS_VERIFY
          value: "false"
        ports:
        - containerPort: 8125
          hostPort: 8125
          name: dogstatsd
          protocol: UDP
        - containerPort: 8126
          hostPort: 8126
          name: traceport
          protocol: TCP
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        volumeMounts:
        - name: containerdsocket
          mountPath: /var/run/containerd/containerd.sock
        - name: procdir
          mountPath: /host/proc
          readOnly: true
        readinessProbe:
          exec:
            command: ["/opt/datadog-agent/bin/agent/agent", "health"]
          initialDelaySeconds: 15
          periodSeconds: 15
        livenessProbe:
          exec:
            command: ["/opt/datadog-agent/bin/agent/agent", "health"]
          initialDelaySeconds: 15
          periodSeconds: 15
      volumes:
      - name: containerdsocket
        hostPath:
          path: /var/run/containerd/containerd.sock
          type: Socket
      - name: procdir
        hostPath:
          path: /proc
