package com.ootd.pickup.global.exception;

public enum ClientExceptionCode {
    INTERNAL_SERVER_ERROR,
    ILLEGAL_ARGUMENT,
    PIKACHU_NOT_FOUND,
    CARD_NOT_FOUND,
    MEMBER_LOGIN_ID_ALREADY_EXISTS,
    MEMBER_NICKNAME_ALREADY_EXISTS,
    INVALID_ACCESS_TOKEN,
}
