package com.ootd.pickup.global.exception;

public enum ClientExceptionCode {
  INTERNAL_SERVER_ERROR,
  ILLEGAL_ARGUMENT,
  PIKACHU_NOT_FOUND,
  CARD_NOT_FOUND,
  INVALID_GRADE,
  INVALID_CERTIFICATION_BODY,
  CONSIGNMENT_NOT_FOUND,
  CERTIFICATE_NOT_FOUND,
  MEMBER_NOT_FOUND,
  MEMBER_LOGIN_ID_ALREADY_EXISTS,
  MEMBER_NICKNAME_ALREADY_EXISTS,
  INVALID_ACCESS_TOKEN,
  AUTHENTICATION_REQUIRED,
  INVALID_PASSWORD,
  INVALID_REFRESH_TOKEN,
  CONSIGNMENT_NOT_REGISTERABLE,
  CONSIGNMENT_ACCESS_DENIED,
  INVALID_AUCTION_STATUS,
  INVALID_AUCTION_SORT,
  INVALID_CURSOR,
}
