apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pickup-qa
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: pickup-qa
  source:
    repoURL: https://github.com/softeerbootcamp-8th/WEB-Team5-55TD.git
    targetRevision: for-qa
    path: k8s/overlays/qa
  destination:
    server: https://kubernetes.default.svc
    namespace: pickup-qa
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
