## 설치 경로: /etc/systemd/system/pickup.service.d/datadog.conf
[Service]
Environment="DD_PROFILING_ENABLED=true"
Environment="DD_LOGS_ENABLED=true"
Environment="DD_LOGS_INJECTION=true"
Environment="DD_TRACE_DB_CLIENT_SPLIT_BY_INSTANCE=true"
Environment="DD_JMXFETCH_CONFIG_DIR=/opt/datadog/jmx"
Environment="DD_JMXFETCH_CONFIG=hikaricp.yaml,tomcat.yaml,websocket.yaml"
Environment="DD_JMXFETCH_CHECK_PERIOD=15000"
Environment="DD_JMXFETCH_REFRESH_BEANS_PERIOD=60"
