apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pickup-qa
resources:
  - namespace.yaml
  - ../../base
images:
  - name: pickup-api
    newName: ghcr.io/softeerbootcamp-8th/web-team5-55td/pickup-api
    newTag: 80f14b6d33feca5d866525f88baa0399ad0ed608
  - name: pickup-web
    newName: ghcr.io/softeerbootcamp-8th/web-team5-55td/pickup-web
    newTag: 80f14b6d33feca5d866525f88baa0399ad0ed608
labels:
  - pairs:
      app.kubernetes.io/part-of: pickup
      app.kubernetes.io/environment: qa
