apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pickup-qa
resources:
  - namespace.yaml
  - ../../base
images:
  - name: pickup-api
    newName: ghcr.io/softeerbootcamp-8th/web-team5-55td/pickup-api
    newTag: eacc85fbce16416cf2a44c007431c45b70a397da
  - name: pickup-web
    newName: ghcr.io/softeerbootcamp-8th/web-team5-55td/pickup-web
    newTag: eacc85fbce16416cf2a44c007431c45b70a397da
labels:
  - pairs:
      app.kubernetes.io/part-of: pickup
      app.kubernetes.io/environment: qa
