apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pickup-qa
resources:
  - namespace.yaml
  - ../../base
images:
  - name: pickup-api
    newName: ghcr.io/softeerbootcamp-8th/web-team5-55td/pickup-api
    newTag: f581733ac34d1a2168072f197a32adf223d01732
  - name: pickup-web
    newName: ghcr.io/softeerbootcamp-8th/web-team5-55td/pickup-web
    newTag: f581733ac34d1a2168072f197a32adf223d01732
labels:
  - pairs:
      app.kubernetes.io/part-of: pickup
      app.kubernetes.io/environment: qa
